### ISSUE TITLE
请问prometheus-server-configmap的yaml，配置数据源那个是不是重复的两个，xxxx:30090和yyyy:30090有是什么呢？

### ISSUE THREAD

**Issue by yeyuguang1** [xianyuLuo/prometheus-monitor-kubernetes#1]

**Comment by xianyuLuo** [comment]
prometheus-server是数据集中汇总的地方。xxxx:30090和yyyy:30090指的是被监控的k8s集群中部署的prometheus程序，通过这2个地址就可以把x集群和y集群的监控数据pull下来。
如果被监控的k8s集群有N个，这儿也应该配置Ｎ个地址。

**Comment by wchkong** [comment]
这个配置文件的两个job name是一样的，导致我server-dep报错：parsing YAML file /etc/prometheus/config/prometheus.yml: found multiple scrape configs with job name \"federate-sdorica\""，可以加个1,2区分一下
